### ISSUE TITLE
SocketTimeoutException during OAuth flow

### ISSUE THREAD

**Issue by mohammadashrafvora** [gsuitedevs/java-samples#10]
(Please fill out these details before submitting an issue)

### Google Gmail API Java not working as expected while reading mails
I want to read mails from gmail account using Google Gmail API for Java.

I have created a sample Core Java project with code given at google console developer example for gmail app [here](https://github.com/gsuitedevs/java-samples/blob/master/gmail/quickstart/src/main/java/GmailQuickstart.java). 

I ran this code and I am getting "java.net.SocketTimeoutException: Read timed out"exception. Details of implementation is as below:

When I debug above code, on line 67 `return new AuthorizationCodeInstalledApp(flow, new LocalServerReceiver()).authorize("user");` , I get a prompt of browser to login in gmail account to give access to My Project configured in Developer Console.

After I authorize application, it redirects me to url like below:
`http://localhost:25745/Callback?code=4/AABrLErTmOxzKEqqD31iiMftE93i3k06oJ4sAI34uS7jI7U-VAdofx0hV8ZoyzHEJyjFEx6x1VYASMNe779Dpa0#`
and I get message "Received verification code. You may now close this window." on screen.
In url, port gets changed every time.

In code, it tries to request token to start executing gmail operations, but It waits there and Gives below exception:
`Exception in thread "main" java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
	at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:158)
	at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:79)`

Also, I tried to get token manually by sending POST request on ` https://accounts.google.com/o/oauth2/token` with below parameters:
code - Code I received in URL after allowing access to application
client_id - client id of o-auth client
client_secret - client secret of o-auth client
grant_type - authorization_code
redirect_uri - http://localhost

I get below response:
{
    "error": "invalid_grant",
    "error_description": "Bad Request"
}

Anyone knows how I can resolve above error or what I am doing wrong, it will be a great help.

**Comment by erickoledadevrel** [comment]
I'm not sure why you are running into a timeout, but you can increase the timeout length using the code listed here:

https://developers.google.com/api-client-library/java/google-api-java-client/errors#timeouts

**Comment by mohammadashrafvora** [comment]
Link is showing to add timeout in HttpRequestInitializer. 

![image](https://user-images.githubusercontent.com/41424226/42943543-ac3359d0-8b80-11e8-982b-8a33a8463a53.png)

Google API for mail uses Credential class and implements HttpRequestInitializer. and Lines that I marked as yellow are not able to execute because I am getting Credential as null.

Here, this time out will come in picture only after authorise() method completes. But in my case, I am getting time out on line "TokenResponse response = flow.newTokenRequest(code).setRedirectUri(redirectUri).execute();". This line redirects me to url as below: "http://localhost:25745/Callback?code=4/AABrLErTmOxzKEqqD31iiMftE93i3k06oJ4sAI34uS7jI7U-VAdofx0hV8ZoyzHEJyjFEx6x1VYASMNe779Dpa0#"

And this is where exact problem lies and I am not able to execute "return flow.createAndStoreCredential(response, userId);" line. I think If I get TokenResponse, Token will be stored as a file and it should work.

**Comment by erickoledadevrel** [comment]
I see, the timeout there is for the service itself, but this is happening earlier with the OAuth flow. Some more searching indicates this is a proxy issue. Please try the recommended solution here:

https://stackoverflow.com/a/39347143

**Comment by mohammadashrafvora** [comment]
I consulted network team for proxy related details but in our environment proxy is not configured.
I have debugged further into timeout issue and finding are as below:
API is trying to execute redirect url with code and get authentication Token.

**Comment by erickoledadevrel** [comment]
Looking at the stack trace you posted earlier, the timeout is happening when the code tries to make a request to Google's OAuth2 `https://www.googleapis.com/oauth2/v4/token` endpoint, not with the callback URL. See if you can make a request to that URL in your Java environment using other means.

**Comment by erickoledadevrel** [comment]
Closing due to inactivity.
