### ISSUE TITLE
I can't find what is wrong

### ISSUE THREAD

**Issue by Naduni18** [gsuitedevs/java-samples#32]
Microsoft Windows [Version 10.0.17134.285]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\hp>cd\

C:\>cd Users\hp\Desktop\dd

C:\Users\hp\Desktop\dd>gradle -q run
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
Exception in thread "main" java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at CalendarQuickstart.getCredentials(CalendarQuickstart.java:45)
        at CalendarQuickstart.main(CalendarQuickstart.java:59)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_151\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s

C:\Users\hp\Desktop\dd>

**Comment by erickoledadevrel** [comment]
Please see my response in issue #31 .
