### ISSUE TITLE
403 forbidden error

### ISSUE THREAD

**Issue by Visa1704** [gsuitedevs/java-samples#34]
(Please fill out these details before submitting an issue)

### Sample Name
Getting 403 forbidden error while retrieving chromeosdevices

### Expected Behavior
Return all the chrome os devices mapped to the customer id
### Actual Behavior
Throws 403 Forbidden error
### Specifications
  - Java version (1.8)
  - OS (Windows)

**Comment by Visa1704** [comment]
Exceptions on the log:-
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
Sep 25, 2018 1:16:54 PM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNING: unable to change permissions for everybody: \Codespace\Chromebits\ChromebitAPI\tokens
Sep 25, 2018 1:16:55 PM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNING: unable to change permissions for owner: \Codespace\Chromebits\ChromebitAPI\tokens
Exception in thread "main" com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Insufficient Permission",
    "reason" : "insufficientPermissions"
  } ],
  "message" : "Insufficient Permission"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1067)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at AdminSDKReportsQuickstart.main(AdminSDKReportsQuickstart.java:64)

**Comment by erickoledadevrel** [comment]
None of our samples show retrieving Chrome OS devices, so this is likely not a bug in the sample code. Most likely you either forgot to change the scope you are requesting or have forgotten to delete your stored credentials which were only authorized for the previous scope.

**Comment by Shailjakant12** [comment]
How to delete the stored credential?

**Comment by erickoledadevrel** [comment]
As mentioned in the code:

```
If modifying these scopes, delete your previously saved tokens/ folder.
```
