### ISSUE TITLE
Sheets Quickstart GoogleJsonResponseException: 400 Bad Request

### ISSUE THREAD

**Issue by gaabs** [gsuitedevs/java-samples#42]
### Sample Name
Sheets Quickstart

### Expected Behavior
Code should run with no errors, as all the steps listed at https://developers.google.com/sheets/api/quickstart/java were followed.

### Actual Behavior
Execution failed with `GoogleJsonResponseException`. Logs attached below:

```
> Task :run FAILED
Exception in thread "main" com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Unable to parse range: Class DataE",
    "reason" : "badRequest"
  } ],
  "message" : "Unable to parse range: Class DataE",
  "status" : "INVALID_ARGUMENT"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at SheetsQuickstart.main(SheetsQuickstart.java:69)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

### Specifications
  - Java version: `1.8.0_131`
  - OS: Mac

**Comment by gaabs** [comment]
Solved. 
When I copied the main class, it pasted `range = "Class DataE";` instead of `range = "Class Data!A2:E"`, which caused this error. Changing that was enough to fix.
