### ISSUE TITLE
No such method error

### ISSUE THREAD

**Issue by kyawzinhtun** [gsuitedevs/java-samples#47]
(Please fill out these details before submitting an issue)

### Sample Name
Test calendar event

### Expected Behavior
Get all calendar event
### Actual Behavior
Exception in thread "main" java.lang.NoSuchMethodError: com.google.api.client.http.javanet.NetHttpTransport.<init>(Ljava/net/Proxy;Ljavax/net/ssl/SSLSocketFactory;Ljavax/net/ssl/HostnameVerifier;)V
	at com.google.api.client.http.javanet.NetHttpTransport$Builder.build(NetHttpTransport.java:288)
	at com.google.api.client.googleapis.javanet.GoogleNetHttpTransport.newTrustedTransport(GoogleNetHttpTransport.java:56)
	at maventest.maventest.CalendarQuickstart.main(CalendarQuickstart.java:61)
### Specifications
  - Java 8
  - OS  Window

**Comment by erickoledadevrel** [comment]
I'm not able to reproduce this problem, but some Google searches seem to indicate the problem is related to outdated dependencies. Please ensure you do a clean build and aren't relying on any other libraries that would be using an older version of those dependencies.

**Comment by kyawzinhtun** [comment]
Hi Erick,

Thanks for your reply. 
According to your suggestion when I change to dependency version 1.27 to 1.23, It was okay.
Thank you.
