### ISSUE TITLE
Exception in thread "main" java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by surersen** [gsuitedevs/java-samples#51]
(Please fill out these details before submitting an issue)

### Sample Name
(i.e. Gmail Quickstart)

### Specifications
  - Java version (`java -1.8.0_161`)
  - OS (Windows)

$ gradle -q run
12 17, 2018 8:55:29 ▒ߑO com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
▒x▒▒: unable to change permissions for everybody: D:\Project\Intellij\gdriveapi\tokens
12 17, 2018 8:55:29 ▒ߑO com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
▒x▒▒: unable to change permissions for owner: D:\Project\Intellij\gdriveapi\tokens
2018-12-17 08:55:30.008:INFO::Logging to STDERR via org.mortbay.log.StdErrLog
2018-12-17 08:55:30.008:INFO::jetty-6.1.26
2018-12-17 08:55:30.024:INFO::Started SocketConnector@localhost:8888
Please open the following address in your browser:
  https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=1008108164994-ctl79pjeg76ifeo2quj52inqq2hvb32e.apps.googleusercontent.com&redirect_uri=http://localhost:8888/Callback&response_type=code&scope=https://www.googleapis.com/auth/drive.metadata.readonly
Attempting to open that address in the default browser now...
2018-12-17 08:56:00.976:INFO::Stopped SocketConnector@localhost:8888
Exception in thread "main" java.net.SocketTimeoutException: connect timed out
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
        at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:158)
        at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:79)
        at com.google.api.client.extensions.java6.auth.oauth2.AuthorizationCodeInstalledApp.authorize(AuthorizationCodeInstalledApp.java:84)
        at DriveQuickstart.getCredentials(DriveQuickstart.java:53)
        at DriveQuickstart.main(DriveQuickstart.java:59)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'D:\Program Files\Java\jdk1.8.0_161\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s

**Comment by erickoledadevrel** [comment]
Sorry for the long delay. A likely cause is that you had something else running on port 8888.
