### ISSUE TITLE
Google Calendar Event Sorting error

### ISSUE THREAD

**Issue by ivank2017** [gsuitedevs/java-samples#52]
(Please fill out these details before submitting an issue)
```
events.list(CALENDAR_MAIN).setOrderBy("startTime").setTimeMin(startDtTime).setTimeMax(endDtTime).execute();
```
### Sample Name
```
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "orderBy",
    "locationType" : "parameter",
    "message" : "The requested ordering is not available for the particular query.",
    "reason" : "invalid"
  } ],
  "message" : "The requested ordering is not available for the particular query."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
```

### Expected Behavior
Method should return sorted collection 
### Actual Behavior
i get an error
### Specifications
  - Java version (`java -version`) JDK 8
  - OS (Mac/Linux/Windows) windows

**Comment by erickoledadevrel** [comment]
This issue tracker is only for reporting bugs with our samples. This seems to be your own custom code. Please see the [Calendar API support page](https://developers.google.com/calendar/support) for the available support options.
