### ISSUE TITLE
Exception in main thread 

### ISSUE THREAD

**Issue by KopalMehrotra** [gsuitedevs/java-samples#60]
(Please fill out these details before submitting an issue)

Exception in thread "main" java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at DriveQuickstart.getCredentials(DriveQuickstart.java:44)
	at DriveQuickstart.main(DriveQuickstart.java:59)

**Comment by erickoledadevrel** [comment]
This error indicates that the code can't find the credentials.json file. Please ensure it was placed into the correct directory.
