### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by rockingA** [gsuitedevs/java-samples#61]
Copied same to same from https://developers.google.com/calendar/quickstart/java
### Specifications
  - Java version (1.8)
  - OS - MAC

Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:37)
	at com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets.getDetails(GoogleClientSecrets.java:82)
	at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow$Builder.<init>(GoogleAuthorizationCodeFlow.java:195)
	at com.api.service.CalendarQuickstart.getCredentials(CalendarQuickstart.java:50)
	at com.api.service.CalendarQuickstart.main(CalendarQuickstart.java:60)

**Comment by erickoledadevrel** [comment]
This error indicates that you downloaded the wrong type of `credentials.json` file. Please use the button in the quickstart instruction to download a file with the type "Installed application."
