### ISSUE TITLE
SheetsQuickstart is not working with Maven.

### ISSUE THREAD

**Issue by Maktag** [gsuitedevs/java-samples#70]
(Please fill out these details before submitting an issue)

### Sample Name
(i.e. Gmail Quickstart)
Gsheet read api

### Actual Behavior
Giving me the error

Exception in thread "main" java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at data.SheetsQuickstart.getCredentials(SheetsQuickstart.java:47)
	at data.SheetsQuickstart.getdata(SheetsQuickstart.java:62)
	at data.SheetsQuickstart.main(SheetsQuickstart.java:72)

### Specifications
  - Java version (`1.8`)
  - OS (Mac/Linux/Windows) - Mac

**Comment by erickoledadevrel** [comment]
This error occurs when the program can't find the `credentials.json` file. I've updated the code to make it clearer.
