### ISSUE TITLE
IllegalArgumentException being thrown when trying to authenticate with google sheets api

### ISSUE THREAD

**Issue by aeslami3574** [gsuitedevs/java-samples#93]
(Please fill out these details before submitting an issue)

### Sample Name
Modified version of https://developers.google.com/sheets/api/quickstart/java
```java
private Credential getCredentials(NetHttpTransport httpTransport) {
    try {
        GoogleClientSecrets clientSecrets = GoogleClientSecrets.load(JSON_FACTORY, new InputStreamReader(new FileInputStream(credentialsFilePath)));
        GoogleAuthorizationCodeFlow flow = new GoogleAuthorizationCodeFlow.Builder(httpTransport, JSON_FACTORY, clientSecrets, SCOPES)
                .setDataStoreFactory(new FileDataStoreFactory(new File(credentialsFilePath))).setAccessType("offline")
                .build();
        return new AuthorizationCodeInstalledApp(flow, new LocalServerReceiver.Builder().setPort(8888).build()).authorize("user");
    } catch (IOException e) {
        e.printStackTrace();
        return null;
    }
}
```

### Expected Behavior
Was expecting to receive a ``Credential`` object after successfully authenticating with the google api

### Actual 
```java
Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:37)
	at com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets.getDetails(GoogleClientSecrets.java:82)
	at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow$Builder.<init>(GoogleAuthorizationCodeFlow.java:195)
```

### Specifications
  - Java version: 11.0.5
  - OS: Linux (Debian 10.2 Buster)

**Comment by sqrrrl** [comment]
Check your client secrets file to make sure it's correct. Possible that you downloaded credentials in the wrong form.

That error indicates it's not in the expected format as isn't either for a server-side web app or installed (desktop) app. Corresponding code: https://github.com/googleapis/google-api-java-client/blob/master/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleClientSecrets.java

**Comment by sqrrrl** [comment]
Ping @aeslami3574 -- please verify your credentials are the correct type. Otherwise will close issue as not reproducible.

**Comment by cdolek** [comment]
I am having the same issue using the `credentials.json` I have downloaded for a service account.

**Comment by Johnny850807** [comment]
My solutions: Don't use the client secrets, instead, directly build the credentials.

Import this library 
```xml
<dependency>
        <groupId>com.google.auth</groupId>
        <artifactId>google-auth-library-oauth2-http</artifactId>
        <version>1.3.0</version>
</dependency>
```

```java
InputStream in = SheetsQuickstart.class.getResourceAsStream(CREDENTIALS_FILE_PATH);
if (in == null) {
        throw new FileNotFoundException("Resource not found: " + CREDENTIALS_FILE_PATH);
}
GoogleCredentials googleCredentials = GoogleCredentials.fromStream(in).createScoped(SCOPES);

Sheets service = new Sheets.Builder(HTTP_TRANSPORT, JSON_FACTORY, new HttpCredentialsAdapter(googleCredentials))
                .setApplicationName(APPLICATION_NAME)
                .build();
```

**Comment by WeeHong** [comment]
> My workaround: Don't use the client secrets, instead, directly build the credentials.
> 
> Import this library
> 
> ```
> <dependency>
>         <groupId>com.google.auth</groupId>
>         <artifactId>google-auth-library-oauth2-http</artifactId>
>         <version>1.3.0</version>
> </dependency>
> ```
> 
> ```java
> InputStream in = SheetsQuickstart.class.getResourceAsStream(CREDENTIALS_FILE_PATH);
> if (in == null) {
>         throw new FileNotFoundException("Resource not found: " + CREDENTIALS_FILE_PATH);
> }
> GoogleCredentials googleCredentials = GoogleCredentials.fromStream(in).createScoped(SCOPES);
> 
> Sheets service = new Sheets.Builder(HTTP_TRANSPORT, JSON_FACTORY, new HttpCredentialsAdapter(googleCredentials))
>                 .setApplicationName(APPLICATION_NAME)
>                 .build();
> ```

This is the most relevant answer until today.
Hopefully, more developers can see this.

**Comment by velikanov** [comment]
> My workaround: Don't use the client secrets, instead, directly build the credentials.
> 
> Import this library
> 
> ```
> <dependency>
>         <groupId>com.google.auth</groupId>
>         <artifactId>google-auth-library-oauth2-http</artifactId>
>         <version>1.3.0</version>
> </dependency>
> ```
> 
> ```java
> InputStream in = SheetsQuickstart.class.getResourceAsStream(CREDENTIALS_FILE_PATH);
> if (in == null) {
>         throw new FileNotFoundException("Resource not found: " + CREDENTIALS_FILE_PATH);
> }
> GoogleCredentials googleCredentials = GoogleCredentials.fromStream(in).createScoped(SCOPES);
> 
> Sheets service = new Sheets.Builder(HTTP_TRANSPORT, JSON_FACTORY, new HttpCredentialsAdapter(googleCredentials))
>                 .setApplicationName(APPLICATION_NAME)
>                 .build();
> ```

Works like a charm!
If you see this - use this

THANK YOU @Johnny850807 
Hey @google come on, update your docs!
