### ISSUE TITLE
java.lang.IllegalArgumentException while running DriveQuickstart

### ISSUE THREAD

**Issue by Bikeshtri** [gsuitedevs/java-samples#99]
```
Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:37)
	at com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets.getDetails(GoogleClientSecrets.java:82)
	at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow$Builder.<init>(GoogleAuthorizationCodeFlow.java:195)
	at com.googledriveexample.googledriveexample.DriveQuickstart.getCredentials(DriveQuickstart.java:53)
	at com.googledriveexample.googledriveexample.DriveQuickstart.main(DriveQuickstart.java:65)

```

**Comment by Bikeshtri** [comment]
It was my issue i have selected web application instead of desktop application
